name: Run Integration Tests

on:
  push:
    branches:
      - main 
    paths:
      - '**' 

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set execute permissions for script
        working-directory: ./backend
        run: bash scripts/run_tests.sh